channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - cudatoolkit=11.3
  - pip
  - python=3.8
  - pip:
    - tqdm
    - hydra-core
    - pandas
    - pillow
    - omegaconf>=2.0.0
    - pytorch-lightning>=1.0.8
    - einops
    - transformers
