seed: 424242

model_name: Salesforce/blip-image-captioning-large

mnt_dir_path: /mnt/home
data_path: ${mnt_dir_path}/data/diffusiondb_img
index_path: ${mnt_dir_path}/sd_t/sd1_data/index.csv

train_batch_size: 4
valid_batch_size: 8
n_workers: 4

train_size: 1_000_000
val_size: 1_000
epochs: 100
epoch_length: 250
patience: 3

t_max: 500
min_lr: 1e-6
n_accumulate: 1
weight_decay: 1e-6
learning_rate: 1e-5

device: cuda

tracking_uri: ${mnt_dir_path}/mlruns
experiment_name: "blip-image-captioning"
use_mlflow: True

checkpoints_dir_path: null  # needed if not using mlflow
is_cluster: False